# Generated by Django 4.2.7 on 2024-07-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallticket', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('std', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telugu', models.FloatField()),
                ('hindi', models.FloatField()),
                ('english', models.FloatField()),
                ('maths', models.FloatField()),
                ('science', models.FloatField()),
                ('social', models.FloatField()),
                ('total', models.FloatField(default=0, editable=False)),
                ('Avg', models.FloatField(default=0, editable=False)),
                ('grade', models.CharField(default='', editable=False, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
